version: '3.7'

services:

  backend:
    build:
      context: ../
      dockerfile: ci/docker/app/Dockerfile
    restart: on-failure
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - "../app/:/var/app/"
    depends_on:
      - psql
    env_file:
      - docker/app/docker-compose.env

  psql:
    image: postgres:13-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - "psql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}

volumes:
  psql_data: {}
